CREATE TABLE [dbo].[UserWiseCompany]
(
	ItemID INT IDENTITY(1,1) NOT NULL,
	UserID INT NOT NULL,
	CompanyID INT NOT NULL,
	CompanyName VARCHAR(50) NOT NULL,
	[Status] INT NOT NULL,
	CONSTRAINT [PK_UserWiseCompany] PRIMARY KEY CLUSTERED 
	(
		[ItemID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]