USE [ArlaCompass]
GO

CREATE TABLE [dbo].[MobileSalesEligibleSalespoint](
	PKID INT IDENTITY(1,1) NOT NULL,
	SalesPointID INT NULL,
	Code VARCHAR(15) NOT NULL,
	[Name] VARCHAR(75) NOT NULL,
	[Status] INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate DATETIME NOT NULL CONSTRAINT [DF_MobileSalesEligible_CreatedDate]  DEFAULT (getdate()),
	ModifiedBy INT NULL,
	ModifiedDate DATETIME NULL
PRIMARY KEY CLUSTERED 
(
	[PKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
