USE [UnileverOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[GetInvoiceNo]
@StartDate DATETIME, @EndDate DATETIME
AS 
SET NOCOUNT ON;

--DECLARE @StartDate DATETIME = '7 Sep 2021', @EndDate DATETIME = '7 Sep 2021'

SELECT InvoiceID, InvoiceNo FROM SAPInvoices
WHERE CAST(CreatedDate AS DATETIME) BETWEEN CAST(@StartDate AS DATETIME) AND CAST(@EndDate AS DATETIME)
AND InvoiceStatus = 2
